### ISSUE TITLE
作为一个小白，我想问问这个要怎么使用

### ISSUE THREAD

**Issue by zhanght021** [yan12125/iqiyi-hack#3]
作为一个小白，我想问问这个要怎么使用

楼楼你可以具体说一下子吗    @yan12125

**Comment by yan12125** [comment]
看[README](https://github.com/yan12125/iqiyi-hack/blob/master/README.md)。很久沒測試了，不確定這些步驟是不是還能用。

**Comment by zhanght021** [comment]
这个再windows系统上可以用吗， @yan12125

**Comment by yan12125** [comment]
Windows系統請看 https://github.com/xyuanmu/hack-iqiyi ，原理是類似的。

**Comment by zhanght021** [comment]
@yan12125 他那个运行过程中一直报错，感觉哪里有问题
一直提示 patch.exe 已停止工作
｛日志名称: Application
来源: Application Error
日期: 2016/6/10 22:26:57
事件 ID: 1000
任务类别: (100)
级别: 错误
关键字: 经典
用户: 暂缺
计算机: WQ-20160607UJKK
描述:
错误应用程序名称: patch.exe，版本: 0.0.0.0，时间戳: 0x382892a0
错误模块名称: msvcrt.dll，版本: 7.0.7601.17744，时间戳: 0x4eeaf722
异常代码: 0x40000015
错误偏移量: 0x0006680c
错误进程 ID: 0x1b04
错误应用程序启动时间: 0x01d1c32423f9f681
错误应用程序路径: C:\Users\Administrator\Desktop\hack-iqiyi-master\tool\patch.exe
错误模块路径: C:\Windows\syswow64\msvcrt.dll
报告 ID: 62aedd29-2f17-11e6-93a6-a0b3cc264ad2
事件 Xml:

｝

**Comment by yan12125** [comment]
可能他自帶的patch.exe有問題，可以到 http://gnuwin32.sourceforge.net/packages/patch.htm 下載最新版試試。

**Comment by zhanght021** [comment]
谢谢你的帮助                    @yan12125

**Comment by yan12125** [comment]
不會
